#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-2.0-only

START=65
STOP=35
USE_PROCD=1

PROG=/usr/libexec/rg-ma2820/neighbor-sync

start_service()
{
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 5 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
