#!/bin/sh /etc/rc.common
# Vendor-kernel-safe OpenWrt sysntpd service (no namespaces/ujail).

START=98
USE_PROCD=1
PROG=/usr/sbin/ntpd
HOTPLUG_SCRIPT=/usr/sbin/ntpd-hotplug

get_dhcp_ntp_servers()
{
	local interfaces="$1" filter='*' interface ntpservers ntpserver entry duplicate
	for interface in $interfaces; do
		[ "$filter" = '*' ] && filter="@.interface='$interface'" || filter="$filter,@.interface='$interface'"
	done
	ntpservers="$(ubus call network.interface dump |
		jsonfilter -e "@.interface[$filter]['data']['ntpserver']")"
	for ntpserver in $ntpservers; do
		duplicate=0
		for entry in $server; do
			[ "$ntpserver" = "$entry" ] && duplicate=1
		done
		[ "$duplicate" = 0 ] && server="$server $ntpserver"
	done
}

validate_ntp_section()
{
	uci_load_validate system timeserver "$1" "$2" \
		'dhcp_interface:list(string)' \
		'enable_server:bool:0' \
		'enabled:bool:1' \
		'interface:string' \
		'server:list(host)' \
		'use_dhcp:bool:1'
}

start_ntpd_instance()
{
	local peer ifname
	[ "$2" = 0 ] || return 1
	[ "$enabled" = 0 ] && return 0
	[ "$use_dhcp" = 1 ] && get_dhcp_ntp_servers "$dhcp_interface"
	[ -n "$server" ] || [ "$enable_server" != 0 ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" -n -N
	if [ "$enable_server" = 1 ]; then
		procd_append_param command -l
		if [ -n "$interface" ]; then
			network_get_device ifname "$interface" || ifname="$interface"
			procd_append_param command -I "$ifname"
			procd_append_param netdev "$ifname"
		fi
	fi
	[ ! -x "$HOTPLUG_SCRIPT" ] || procd_append_param command -S "$HOTPLUG_SCRIPT"
	for peer in $server; do
		procd_append_param command -p "$peer"
	done
	procd_set_param respawn
	procd_close_instance
}

start_service()
{
	. /lib/functions/network.sh
	validate_ntp_section ntp start_ntpd_instance
}

service_triggers()
{
	local use_dhcp enable_server interface n ifname
	procd_add_config_trigger config.change system /etc/init.d/sysntpd reload
	config_load system
	config_get use_dhcp ntp use_dhcp 1
	if [ "$use_dhcp" = 1 ]; then
		local dhcp_interface
		config_get dhcp_interface ntp dhcp_interface
		if [ -n "$dhcp_interface" ]; then
			for n in $dhcp_interface; do
				procd_add_interface_trigger 'interface.*' "$n" /etc/init.d/sysntpd reload
			done
		else
			procd_add_raw_trigger 'interface.*' 1000 /etc/init.d/sysntpd reload
		fi
	fi
	config_get_bool enable_server ntp enable_server 0
	config_get interface ntp interface
	if [ "$enable_server" = 1 ] && [ -n "$interface" ]; then
		network_get_device ifname "$interface" || ifname="$interface"
		procd_add_interface_trigger 'interface.*' "$ifname" /etc/init.d/sysntpd reload
	fi
	procd_add_validation validate_ntp_section
}
